project:
  type: website

website:
  title: "Prabin Nepal"
  description: "Personal website of Prabin Nepal"
  site-url: https://nepalprabin.github.io
  repo-url: https://github.com/nepalprabin/nepalprabin.github.io
  google-analytics: "G-5HCLVN4PVB"
  open-graph: true
  navbar:
    right:
      # - about.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/nepalprabin
      # - icon: linkedin
      #   href: https://linkedin.com/in/prabin-nepal
format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css

execute:
  freeze: auto
